"""Fit the model to the panel, validate it, and write results.md plus figures.

    python scripts/run_analysis.py
"""

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from merton import crosssection as xs
from merton.analysis import figures, timeseries, validation
from merton.analysis.fit import fit_panel, summarize_coverage

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
FIG_DIR = ROOT / "figures"

log = logging.getLogger("run_analysis")

SCORES = {          # score -> is a higher value safer?
    "dd": True,
    "altman_z": True,
    "leverage_book": False,
    "sigma_E": False,
}
SCORE_LABELS = {
    "dd": "Merton distance-to-default",
    "altman_z": "Altman Z-score",
    "leverage_book": "Book leverage (debt/assets)",
    "sigma_E": "Equity volatility",
}


def md_table(frame: pd.DataFrame, floatfmt: str = "{:.3f}") -> str:
    """Render a frame as a markdown table without pulling in another dependency."""
    def cell(v):
        if isinstance(v, float):
            return floatfmt.format(v)
        if isinstance(v, pd.Timestamp):
            return v.date().isoformat()
        return str(v)

    header = "| " + " | ".join(str(c) for c in frame.columns) + " |"
    align = "|" + "|".join("---:" if pd.api.types.is_numeric_dtype(frame[c]) else "---"
                           for c in frame.columns) + "|"
    rows = ["| " + " | ".join(cell(v) for v in row) + " |"
            for row in frame.itertuples(index=False)]
    return "\n".join([header, align, *rows])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--panel", default=str(DATA_DIR / "panel.parquet"))
    parser.add_argument("--out", default=str(ROOT / "results.md"))
    parser.add_argument("--boot", type=int, default=300)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s",
                        datefmt="%H:%M:%S")

    panel = fit_panel(pd.read_parquet(args.panel))
    fitted = panel[panel["converged"]].copy()
    FIG_DIR.mkdir(exist_ok=True)

    coverage = summarize_coverage(panel)
    log.info("coverage:\n%s", coverage.to_string(index=False))

    # -- discrimination -------------------------------------------------
    comparison = validation.score_comparison(fitted, SCORES, n_boot=args.boot)
    comparison["score"] = comparison["score"].map(SCORE_LABELS).fillna(comparison["score"])
    log.info("score comparison:\n%s", comparison.to_string(index=False))

    deciles = validation.decile_table(fitted, "dd")
    calibration = validation.empirical_vs_model_pd(fitted)

    combined = validation.logistic_benchmark(
        fitted, ["dd", "altman_z", "leverage_book", "log_assets"])
    dd_only = validation.logistic_benchmark(fitted, ["dd"])
    accounting_only = validation.logistic_benchmark(
        fitted, ["altman_z", "leverage_book", "log_assets"])

    # -- credit cycle ---------------------------------------------------
    monthly = timeseries.with_market_spreads(timeseries.aggregate_by_month(fitted))
    correlations = timeseries.cycle_correlations(monthly)
    gaps = timeseries.spread_gap(fitted, monthly)

    # -- figures --------------------------------------------------------
    figures.roc_figure(fitted, SCORES, SCORE_LABELS, FIG_DIR / "roc.png")
    figures.decile_figure(fitted, FIG_DIR / "decile_default_rate.png")
    figures.calibration_figure(fitted, FIG_DIR / "pd_calibration.png")
    figures.event_study_figure(fitted, FIG_DIR / "event_study.png")
    figures.credit_cycle_figure(monthly, FIG_DIR / "credit_cycle.png")
    figures.leverage_vol_figure(fitted, FIG_DIR / "leverage_vs_volatility.png")
    log.info("wrote figures to %s", FIG_DIR)

    # -- rating cross-section -------------------------------------------
    ratings = xs.analyze(xs.load_companies())

    sections = [
        "# Results",
        "",
        "Generated by `scripts/run_analysis.py`. Every number below comes from the "
        "committed panel; nothing is transcribed by hand.",
        "",
        "## 1. What the panel contains",
        "",
        md_table(coverage),
        "",
        "## 2. Does distance-to-default predict bankruptcy?",
        "",
        f"Common sample: {comparison.attrs['n_obs']:,} firm-months, "
        f"{comparison.attrs['n_defaults']:,} of them followed by a bankruptcy filing "
        "within twelve months. Confidence intervals are bootstrapped over firms, "
        "not rows.",
        "",
        md_table(comparison),
        "",
        "![ROC curves](figures/roc.png)",
        "",
        "### Realized default rate by distance-to-default decile",
        "",
        md_table(deciles[["bucket", "n", "defaults", "default_rate_pct",
                          "score_low", "score_high"]], "{:.2f}"),
        "",
        "![Default rate by decile](figures/decile_default_rate.png)",
        "",
        "### Does the structural measure add anything to accounting ratios?",
        "",
        "Out-of-sample AUC from logistic models, five folds split by firm so that no "
        "firm appears in both training and test:",
        "",
        md_table(pd.DataFrame([
            {"model": "Distance-to-default alone", "auc": dd_only["auc"], "n": dd_only["n"]},
            {"model": "Accounting ratios only", "auc": accounting_only["auc"],
             "n": accounting_only["n"]},
            {"model": "Both", "auc": combined["auc"], "n": combined["n"]},
        ])),
        "",
        "## 3. Are the probabilities themselves any good?",
        "",
        "Model risk-neutral PD against the frequency actually realized, by "
        "distance-to-default bucket:",
        "",
        md_table(calibration[["bucket", "n", "dd_mid", "model_pd", "empirical_pd", "ratio"]],
                 "{:.6f}"),
        "",
        "![Model PD vs realized frequency](figures/pd_calibration.png)",
        "",
        "## 4. Distance-to-default approaching a filing",
        "",
        "![Event study](figures/event_study.png)",
        "",
        "## 5. Does the model track the credit cycle?",
        "",
        md_table(correlations),
        "",
        "![Credit cycle](figures/credit_cycle.png)",
        "",
        "Model-implied spread against traded index spreads, selected months:",
        "",
        md_table(gaps[["median_spread", "hy_oas", "bbb_oas", "ratio_bbb_oas"]]
                 .dropna().iloc[::12].reset_index()
                 .rename(columns={"date": "month"}), "{:.4f}"),
        "",
        "## 6. Rating cross-section",
        "",
        f"Spearman rank correlation between model distance-to-default and S&P issuer "
        f"rating across the {len(ratings)} hand-built names: "
        f"**{xs.rating_rank_correlation(ratings):.2f}**.",
        "",
        xs.render_table(ratings, markdown=True),
        "",
        xs.render_rating_summary(ratings, markdown=True),
        "",
        "## 7. What drives the ranking",
        "",
        "![Leverage vs volatility](figures/leverage_vs_volatility.png)",
        "",
    ]

    Path(args.out).write_text("\n".join(sections))
    log.info("wrote %s", args.out)


if __name__ == "__main__":
    main()
